---
name: Math-Polynomial-Solve
version: 2.52
author:
  - 'John M. Gamble <jgamble@cpan.org>'
abstract: Find the roots of polynomial equations.
license: perl
resources:
  license: ~
requires:
  Math::Complex: 1.36
  perl: 5.6.0
build_requires:
  Test::Simple: 0
provides:
  Math::Polynomial::Solve:
    file: lib/Math/Polynomial/Solve.pm
    version: 2.52
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
