---
name: Math-Polynomial-Solve
version: 2.10
author:
  - 'John M. Gamble <jgamble@ripco.com>'
abstract: Find the roots of polynomial equations.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.6.0
build_requires:
  Test::Simple: 0
provides:
  Math::Polynomial::Solve:
    file: lib/Math/Polynomial/Solve.pm
    version: 2.10
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
