# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-Polynomial-Solve
version:      2.11
version_from: lib/Math/Polynomial/Solve.pm
installdirs:  site
requires:
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
