---
name: Math-Polynomial-Solve
version: 2.60
author:
  - 'John M. Gamble <jgamble@cpan.org>'
abstract: Find the roots of polynomial equations.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Simple: 0
requires:
  Math::Complex: 1.36
  perl: v5.6.0
configure_requires:
  Module::Build: 0.340201
provides:
  Math::Polynomial::Solve:
    file: lib/Math/Polynomial/Solve.pm
    version: 2.60
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keyword:
  - math
  - polynomial
  - Sturm
  - Nickalls
  - Laguerre
