---
abstract: 'Find the Roots of Polynomial Equations'
author:
  - 'John M. Gamble <jgamble@cpan.org>'
build_requires:
  Test::Simple: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 0
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Polynomial-Solve
provides:
  Math::Polynomial::Solve:
    file: lib/Math/Polynomial/Solve.pm
    version: 2.67
requires:
  Math::Complex: 1.36
  perl: v5.8.3
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jgamble/Math-Polynomial-Solve.git
version: 2.70
x_keyword:
  - math
  - polynomial
  - quadratic
  - cubic
  - quartic
  - matrix
  - companion-matrix
  - Sturm
  - Nickalls
  - Ferrari
  - Laguerre
  - Hessenberg
  - Newton-Raphson
