---
abstract: 'Find the Roots of Polynomial Equations'
author:
  - 'John M. Gamble <jgamble@cpan.org>'
build_requires:
  Test::Simple: '0'
configure_requires:
  Module::Build: '0.4'
dynamic_config: 0
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-Polynomial-Solve
provides:
  Math::Polynomial::Solve:
    file: lib/Math/Polynomial/Solve.pm
    version: '2.71'
requires:
  Math::Complex: '1.36'
  Math::Utils: '1.06'
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jgamble/Math-Polynomial-Solve.git
version: '2.71'
